const anvilPanel=document.createElement('section');anvilPanel.className='notice anvil-panel';
anvilPanel.innerHTML=`<h2>모루 표시</h2><div class="form-grid"><label>리플레이 대상 (0부터 인덱스 / Riot ID)<input id="anvil-player" value="0"></label><label>근접·원거리 조건<select id="anvil-range"><option value="melee">근접</option><option value="ranged">원거리</option></select></label><label>코어 결과 JSON 불러오기<input id="anvil-json" type="file" accept=".json"></label><button id="anvil-import">선택한 ROFL에서 모루 추출</button><label>선택 라운드 파편검 증폭 (%)<input id="anvil-amplifier" type="number" min="0" max="10000" step="0.1" value="0"></label><button id="anvil-propagate">이후 라운드에도 같은 값 적용</button><label>합계 구간 시작<input id="anvil-start" value="00:00"></label><label>합계 구간 종료<input id="anvil-end" value="10:00"></label><label>미리보기 시각<input id="anvil-time" value="00:00"></label><button id="anvil-play">효과 재생</button></div><p class="muted">전투 전환 시간을 기준으로 이번 라운드 합계를 총합에 합칩니다. 각 모루에 해당 라운드의 증폭을 적용하며, 같은 값 적용은 이후 라운드의 입력값을 덮어씁니다. 기본 스탯 기준의 합산입니다. 유료 구매 여부는 코어에서 확인되지 않아 무료 지급도 포함됩니다. 전투 전환 시간이 없는 라운드는 합산 대기 상태입니다.</p><label>현재 모루<select id="anvil-event"></select></label><label>현재 모루 기본 스탯 보정 (JSON)<input id="anvil-correction" placeholder='{"attackDamage":15}'></label><label class="overlay-check"><input id="anvil-exclude" type="checkbox">이 알림 합계에서 제외</label><p id="anvil-detail" class="muted"></p><div class="checkerboard"><div id="anvil-canvas" class="anvil-canvas"></div></div><p id="anvil-interval"></p><div class="actions"><button id="anvil-png">모루 투명 PNG 저장</button><button id="anvil-mov">모루 투명 MOV 생성</button></div><p id="anvil-status" role="status"></p>`;
document.querySelector('main').append(anvilPanel);
let anvilEvents=[],anvilRange='melee',anvilTimer=null;
try{const s=JSON.parse(localStorage.getItem('arena-anvils-v1'));if(s){anvilEvents=s.events||[];anvilRange=s.range||'melee';}}catch{}
document.querySelector('#anvil-range').value=anvilRange;
const av=id=>document.getElementById('anvil-'+id),anvilStatus=message=>av('status').textContent=message;
function saveAnvils(){localStorage.setItem('arena-anvils-v1',JSON.stringify({events:anvilEvents,range:anvilRange}));}
function anvilNumber(key,n){return `${Number(n.toFixed(2))}${key.endsWith('Percent')?'%':''}`;}
function anvilRows(state,time){return Object.entries(ArenaAnvil.stats).filter(([key])=>state.total[key]||state.pending[key]||state.current[key]).map(([key,[name,icon]])=>{const age=state.purchaseAge;return `<div class="anvil-row"><img src="imgs/stats/${icon}" alt="${name}" title="${name}"><span class="anvil-total" style="text-shadow:0 0 ${state.mergeAge<.6?(1-state.mergeAge/.6)*18:0}px #ffe89a">${anvilNumber(key,state.total[key]||0)}</span><span class="anvil-plus">+</span><span class="anvil-round" style="color:${age<.45?'#fff3a3':'#92ffbf'}">${state.merging[key]?'':anvilNumber(key,state.pending[key]||0)}${state.merging[key]?`<span class="anvil-merge-ghost" style="opacity:${1-state.mergeAge/.35};transform:translateX(${-state.mergeAge/.35*100}px)">+ ${anvilNumber(key,state.merging[key])}</span>`:''}</span>${state.current[key]?`<span class="anvil-current" style="opacity:${Math.min(1,(1.2-(time-anvilLatest(key,time)))/.3)};transform:translateX(${-Math.max(0,time-anvilLatest(key,time)-.8)*65}px)">+ ${anvilNumber(key,state.current[key])}</span>`:''}</div>`;}).join('')||'<span class="anvil-empty">아직 선택한 모루가 없습니다.</span>';}
function anvilLatest(key,time){return Math.max(...anvilEvents.filter(e=>!e.excluded&&e.time<=time&&ArenaAnvil.base(e,anvilRange)[key]).map(e=>e.time));}
function anvilState(time){return ArenaAnvil.state(anvilEvents,rounds,time,{range:anvilRange,seconds:timeSeconds,start:timeSeconds(av('start').value),end:timeSeconds(av('end').value)});}
function renderAnvils(){try{const t=timeSeconds(av('time').value),s=anvilState(t);av('canvas').innerHTML=anvilRows(s,t);av('interval').textContent='지정 구간 합계 · '+Object.entries(s.interval).map(([k,v])=>`${ArenaAnvil.stats[k][0]} ${anvilNumber(k,v)}`).join(' / ');av('amplifier').value=rounds[selectedRound]?.shardbladePercent||0;}catch(e){anvilStatus(e.message);}}
function anvilSelect(){const e=anvilEvents[Number(av('event').value)];if(!e)return;av('time').value=replayTime(e.time+.1);av('correction').value=e.overrideStats?JSON.stringify(e.overrideStats):'';av('exclude').checked=!!e.excluded;av('detail').textContent=`${e.selectedShard} · ${e.round||'?'}라운드 · ${e.statReference?.recordMode||'스탯 미확인'} · 기본값 ${JSON.stringify(ArenaAnvil.base(e,anvilRange))}${e.statReference?.rewardDecodeStatus?' · '+e.statReference.rewardDecodeStatus:''}`;renderAnvils();}
function loadAnvils(result){if(!Array.isArray(result.events))throw Error('코어의 모루 결과 JSON을 선택하세요.');anvilEvents=result.events.map(e=>{if(!Number.isFinite(e.time)||e.time<0||!e.selectedSpell)throw Error('모루 이벤트 형식이 잘못되었습니다.');return e;}).sort((a,b)=>a.time-b.time);saveAnvils();refreshAnvilEvents();anvilStatus(`${result.player?.riotId||''} · 모루 ${anvilEvents.length}개 · 미해독 ${result.unresolved?.length||0}개`);}
function refreshAnvilEvents(){av('event').innerHTML=anvilEvents.map((e,i)=>`<option value="${i}">${e.round||'?'}R · ${replayTime(e.time)} · ${escapeHTML(e.selectedShard)}</option>`).join('');anvilSelect();renderAnvils();}
av('json').onchange=async()=>{try{loadAnvils(JSON.parse(await av('json').files[0].text()));}catch(e){anvilStatus(e.message);}};
av('import').onclick=async()=>{const b=av('import');b.disabled=true;try{const file=document.querySelector('#replay-upload').files[0];if(!file)throw Error('왼쪽에서 ROFL 파일을 먼저 선택하세요.');if(file.size>64*1024*1024)throw Error('최대 64MB까지 지원합니다.');if(!rounds.length){await document.querySelector('#replay-import').onclick();if(!rounds.length)throw Error('라운드 시간 추출에 실패했습니다. 라운드를 먼저 입력하세요.');}anvilStatus('모루 데이터 추출 중…');const response=await fetch('/api/overlay/replay-anvils?player='+encodeURIComponent(av('player').value),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});if(!response.headers.get('content-type')?.includes('application/json'))throw Error('npm start로 실행한 로컬 서버에서 사용하세요.');const result=await response.json();if(!response.ok)throw Error(result.error);loadAnvils(result);}catch(e){anvilStatus(e.message);}finally{b.disabled=false;}};
av('event').onchange=anvilSelect;
av('range').onchange=()=>{anvilRange=av('range').value;saveAnvils();anvilSelect();};
for(const id of ['time','start','end'])av(id).onchange=renderAnvils;
av('amplifier').onchange=()=>{try{if(!rounds[selectedRound])throw Error('라운드를 먼저 선택하세요.');const n=Number(av('amplifier').value);if(!Number.isFinite(n)||n<0||n>10000)throw Error('증폭은 0~10000%로 입력하세요.');rounds[selectedRound].shardbladePercent=n;saveRounds();renderAnvils();}catch(e){anvilStatus(e.message);}};
av('propagate').onclick=()=>{av('amplifier').onchange();if(!rounds[selectedRound])return;for(let i=selectedRound+1;i<rounds.length;i++)rounds[i].shardbladePercent=rounds[selectedRound].shardbladePercent;saveRounds();renderAnvils();anvilStatus('이후 모든 라운드에 증폭값을 적용했습니다.');};
av('correction').onchange=()=>{try{const e=anvilEvents[Number(av('event').value)];if(!e)return;const v=av('correction').value.trim()?JSON.parse(av('correction').value):null;if(v&&(Array.isArray(v)||typeof v!=='object'||Object.entries(v).some(([k,n])=>!ArenaAnvil.stats[k]||!Number.isFinite(n))))throw Error('지원하는 스탯 이름과 숫자로 입력하세요.');if(v)e.overrideStats=v;else delete e.overrideStats;saveAnvils();anvilSelect();}catch(e){anvilStatus(e.message);}};
av('exclude').onchange=()=>{const e=anvilEvents[Number(av('event').value)];if(e){e.excluded=av('exclude').checked;saveAnvils();renderAnvils();}};
av('play').onclick=()=>{if(anvilTimer){clearInterval(anvilTimer);anvilTimer=null;av('play').textContent='효과 재생';return;}try{const begin=timeSeconds(av('time').value),clock=performance.now();av('play').textContent='재생 정지';anvilTimer=setInterval(()=>{av('time').value=replayTime(begin+(performance.now()-clock)/1000);renderAnvils();},40);}catch(e){anvilStatus(e.message);}};
new MutationObserver(renderAnvils).observe(document.querySelector('#selected-round-heading'),{childList:true});
timelinePanel.addEventListener('input',()=>renderAnvils());
av('png').onclick=async()=>{try{const c=await html2canvas(av('canvas'),{backgroundColor:null,scale:2});const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download=overlayFileName('png').replace('.png','-모루.png');a.click();}catch(e){anvilStatus(e.message);}};
refreshAnvilEvents();
av('mov').onclick=async()=>{
 const button=av('mov'),stage=document.createElement('div');button.disabled=true;
 try{
  if(!anvilEvents.length||!rounds.length)throw Error('모루 데이터와 라운드를 먼저 불러오세요.');
  if(anvilEvents.some(e=>!e.excluded&&!rounds[(e.round||1)-1]?.combatTransition))throw Error('모루가 있는 모든 라운드의 전투 전환 시간을 입력하세요.');
  const fps=Number(document.querySelector('#timeline-fps').value),end=timeSeconds(document.querySelector('#timeline-end').value),total=Math.round(end*fps);
  if(![24,30,60].includes(fps)||!total||end>14400)throw Error('영상 길이와 프레임률을 확인하세요.');
  const keys=new Set(anvilEvents.flatMap(e=>Object.keys(ArenaAnvil.base(e,anvilRange)))),width=640,height=Math.max(64,24+keys.size*44);
  stage.className='anvil-canvas';stage.style.cssText=`position:absolute;left:-16000px;top:0;width:${width}px;height:${height}px;overflow:hidden`;document.body.append(stage);await document.fonts.ready;
  const windows=anvilEvents.filter(e=>!e.excluded).flatMap(e=>{const combat=timeSeconds(rounds[(e.round||1)-1].combatTransition);return [[Math.round(e.time*fps),Math.ceil((e.time+1.65)*fps)],[Math.round(Math.max(e.time,combat)*fps),Math.ceil((Math.max(e.time,combat)+.6)*fps)]];}).filter(([s])=>s<total).map(([s,e])=>[Math.max(0,s),Math.min(total,e)]).sort((a,b)=>a[0]-b[0]);
  const merged=[];for(const w of windows){const last=merged.at(-1);if(last&&w[0]<=last[1])last[1]=Math.max(last[1],w[1]);else merged.push(w);}
  const segments=[];let frame=0,bytes=0;
  const capture=async f=>{const t=f/fps;stage.innerHTML=anvilEvents.some(e=>!e.excluded&&e.time<=t)?anvilRows(anvilState(t),t):'';await Promise.all([...stage.querySelectorAll('img')].map(img=>img.decode()));const canvas=await html2canvas(stage,{backgroundColor:null,scale:1,logging:false});const png=canvas.toDataURL('image/png').split(',')[1];bytes+=png.length;if(bytes>240*1024*1024)throw Error('영상 소스가 너무 큽니다. 프레임률을 낮추거나 알림을 제외하세요.');return png;};
  for(const [start,finish]of merged){if(start>frame)segments.push({frames:start-frame,png:await capture(frame)});frame=start;while(frame<finish){const count=Math.min(180,finish-frame),images=[];for(let i=0;i<count;i++){images.push(await capture(frame+i));if(i%10===0){anvilStatus(`모루 영상 준비 ${Math.round((frame+i)/total*100)}%`);await new Promise(r=>setTimeout(r,0));}}segments.push({frames:count,images});frame+=count;}}
  if(frame<total)segments.push({frames:total-frame,png:await capture(frame)});
  if(segments.length>2001)throw Error('모루 영상 구간이 너무 많습니다.');
  anvilStatus('모루 투명 MOV 인코딩 중…');const response=await fetch('/api/overlay/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fps,width,height,editor:'premiere',codec:'qtrle',segments})});if(!response.headers.get('content-type')?.includes('application/json'))throw Error('로컬 서버에서 사용하세요.');const result=await response.json();if(!response.ok)throw Error(result.error);
  while(true){await new Promise(r=>setTimeout(r,1500));const p=await fetch(`/api/overlay/render/${result.id}`,{cache:'no-store'});if(!p.ok)throw Error('인코딩 서버 연결이 끊겼습니다.');const job=await p.json();if(job.state==='failed')throw Error(job.error);anvilStatus(`모루 MOV 인코딩 ${job.progress}%`);if(job.state==='complete'){const name=overlayFileName('mov').replace('.mov','-모루.mov'),a=document.createElement('a');a.href=`/api/overlay/render/${result.id}/file?filename=${encodeURIComponent(name)}`;a.download=name;a.click();anvilStatus('모루 MOV 생성 완료 · 원본 영상 위에 00:00부터 배치하세요.');break;}}
 }catch(e){anvilStatus(e.message);}finally{stage.remove();button.disabled=false;}
};
