const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{randomUUID}=require('node:crypto');
const root=path.resolve(__dirname,'..'),jobs=new Map();
function ffmpegPath(){if(process.env.FFMPEG_PATH)return process.env.FFMPEG_PATH;const local=path.join(root,'tools/ffmpeg/ffmpeg.exe');if(fs.existsSync(local))return local;return 'ffmpeg';}
function run(args,onProgress){return new Promise((resolve,reject)=>{const child=spawn(ffmpegPath(),args,{windowsHide:true});let error='';child.stderr.on('data',chunk=>{error=(error+chunk).slice(-4000);});child.stdout.on('data',chunk=>{const matches=[...String(chunk).matchAll(/frame=(\d+)/g)];if(matches.length)onProgress?.(Number(matches.at(-1)[1]));});child.on('error',()=>reject(Error('FFmpeg를 찾을 수 없습니다. README의 설치 안내를 확인하세요.')));child.on('close',code=>code===0?resolve():reject(Error('영상 인코딩 실패: '+error.slice(-1000))));});}
function start(payload){if([...jobs.values()].some(job=>job.state==='rendering'))throw Error('영상 생성이 진행 중입니다. 완료 후 다시 시도하세요.');const {fps,width,height,segments,editor}=payload;const codec=payload.codec||'qtrle';if(!['qtrle','prores'].includes(codec))throw Error('지원하지 않는 코덱입니다.');const codecArgs=codec==='qtrle'?['-c:v','qtrle','-pix_fmt','argb','-g',String(fps*10)]:['-c:v','prores_ks','-profile:v','4','-pix_fmt','yuva444p10le','-alpha_bits','16','-vendor','apl0'];if(![24,30,60].includes(fps)||!Number.isInteger(width)||!Number.isInteger(height)||width<280||width>3840||height<1||height>8192||!['premiere','finalcut'].includes(editor)||!Array.isArray(segments)||!segments.length||segments.length>2001)throw Error('영상 설정이 올바르지 않습니다.');let total=0;for(const s of segments){if(!Number.isInteger(s.frames)||s.frames<1)throw Error('라운드 소스가 올바르지 않습니다.');const images=s.images||[s.png];if(!Array.isArray(images)||!images.length||images.length>180||(s.images&&images.length!==s.frames))throw Error('애니메이션 프레임이 올바르지 않습니다.');for(const png of images){if(typeof png!=='string'||png.length>20000000)throw Error('라운드 소스가 올바르지 않습니다.');const image=Buffer.from(png,'base64');if(image.length<24||image.subarray(0,8).toString('hex')!=='89504e470d0a1a0a'||image.readUInt32BE(16)!==width||image.readUInt32BE(20)!==height)throw Error('PNG 영상 크기가 일치하지 않습니다.');}total+=s.frames;}if(total>fps*4*3600)throw Error('영상은 최대 4시간까지 지원합니다.');
 const id=randomUUID(),directory=path.join(root,'exports',id);fs.mkdirSync(directory,{recursive:true});const job={id,state:'rendering',progress:0,editor,directory};jobs.set(id,job);
 (async()=>{const temporary=[];try{let completed=0;for(let i=0;i<segments.length;i++){const mov=path.join(directory,`part-${i}.mov`);let input;if(segments[i].images){segments[i].images.forEach((png,j)=>{const file=path.join(directory,`state-${i}-${String(j).padStart(4,'0')}.png`);fs.writeFileSync(file,Buffer.from(png,'base64'));temporary.push(file);});input=['-framerate',String(fps),'-start_number','0','-i',path.join(directory,`state-${i}-%04d.png`)];}else{const png=path.join(directory,`state-${i}.png`);fs.writeFileSync(png,Buffer.from(segments[i].png,'base64'));temporary.push(png);input=['-loop','1','-framerate',String(fps),'-i',png];}temporary.push(mov);await run(['-y',...input,'-frames:v',String(segments[i].frames),'-an',...codecArgs,'-threads','2','-progress','pipe:1',mov],frame=>job.progress=Math.min(99,Math.floor((completed+frame)/total*100)));completed+=segments[i].frames;delete segments[i].images;delete segments[i].png;}
 const list=path.join(directory,'concat.txt');temporary.push(list);fs.writeFileSync(list,segments.map((s,i)=>`file 'part-${i}.mov'`).join('\n'));await run(['-y','-f','concat','-safe','0','-i',list,'-c','copy','-movflags','+faststart',path.join(directory,'arena-overlay.mov')]);job.state='complete';job.progress=100;job.expiresAt=Date.now()+3600000;}
 catch(e){job.state='failed';job.error=e.message;job.expiresAt=Date.now()+3600000;}finally{for(const file of temporary){try{fs.unlinkSync(file);}catch{}}if(job.state==='failed'){try{fs.rmSync(directory,{recursive:true,force:true,maxRetries:3,retryDelay:100});}catch{}}}})();return id;
}
function cleanup(id){const job=jobs.get(id);if(!job||job.state==='rendering'||job.downloads>0)return false;const base=path.join(root,'exports'),target=path.resolve(job.directory);if(path.dirname(target)!==base||path.basename(target)!==id||!/^[a-f0-9-]{36}$/.test(id))throw Error('Invalid cleanup path');try{fs.rmSync(target,{recursive:true,force:true,maxRetries:3,retryDelay:100});jobs.delete(id);return true;}catch{job.expiresAt=Date.now()+60000;return false;}}
function cleanupStartup(base=path.join(root,'exports')){base=path.resolve(base);if(!fs.existsSync(base))return;if(fs.lstatSync(base).isSymbolicLink()||path.resolve(fs.realpathSync(base)).toLowerCase()!==base.toLowerCase())throw Error('Invalid exports path');for(const entry of fs.readdirSync(base,{withFileTypes:true})){if(!entry.isDirectory()||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(entry.name))continue;const target=path.join(base,entry.name);if(!fs.existsSync(path.join(target,'arena-overlay.mov')))fs.rmSync(target,{recursive:true,force:true});else for(const name of fs.readdirSync(target))if(/^(?:state-\d+(?:-\d+)?\.png|part-\d+\.mov|concat\.txt)$/.test(name))fs.unlinkSync(path.join(target,name));}}
function sweep(){const now=Date.now();for(const [id,job] of jobs)if(job.state!=='rendering'&&job.expiresAt<=now)cleanup(id);const base=path.join(root,'exports');if(!fs.existsSync(base))return;for(const entry of fs.readdirSync(base,{withFileTypes:true})){if(!entry.isDirectory()||!/^[a-f0-9-]{36}$/.test(entry.name)||jobs.has(entry.name))continue;const target=path.join(base,entry.name);try{if(!fs.existsSync(path.join(target,'arena-overlay.mov'))&&now-fs.statSync(target).mtimeMs>3600000)fs.rmSync(target,{recursive:true,force:true,maxRetries:3,retryDelay:100});}catch{}}}
const janitor=setInterval(sweep,60000);janitor.unref();sweep();
module.exports={start,jobs,cleanup,sweep,cleanupStartup};
